config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :my_forms
  resources :auths
  resources :account_histories
  resources :accounts
  resources :suppliers
  resources :contacts
  get '/blog/my_blog'
  get 'home/web_page'
  get '/contact/Phone_No'
  get 'online_job_support/ROR_Job_support'
  get 'online_job_support/Ruby_cucumber_Job_Support'
  get 'online_training/RubyOnRails'
  get 'online_training/ruby_cucumber'
  get '/online_training/Python'
  get 'online_training/html_css_js'
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :supplier, foreign_key: "supplier_id"
	has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
	belongs_to :account, foreign_key: "account_id"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth.rb
class Auth < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  #validates :name, :phone, :email, :address, presence: true
  #validates :email, format: { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i }
  #validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  #validates :email, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/ }
end

app/models/my_form.rb
class MyForm < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_one :account
	has_one :account_history, :through => :account
end

app/controllers/account_histories_controller.rb
class AccountHistoriesController < ApplicationController
  before_action :set_account_history, only: [:show, :edit, :update, :destroy]

  # GET /account_histories
  # GET /account_histories.json
  def index
    @account_histories = AccountHistory.all
  end

  # GET /account_histories/1
  # GET /account_histories/1.json
  def show
  end

  # GET /account_histories/new
  def new
    @account_history = AccountHistory.new
  end

  # GET /account_histories/1/edit
  def edit
  end

  # POST /account_histories
  # POST /account_histories.json
  def create
    @account_history = AccountHistory.new(account_history_params)

    respond_to do |format|
      if @account_history.save
        format.html { redirect_to @account_history, notice: 'Account history was successfully created.' }
        format.json { render :show, status: :created, location: @account_history }
      else
        format.html { render :new }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_histories/1
  # PATCH/PUT /account_histories/1.json
  def update
    respond_to do |format|
      if @account_history.update(account_history_params)
        format.html { redirect_to @account_history, notice: 'Account history was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_history }
      else
        format.html { render :edit }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_histories/1
  # DELETE /account_histories/1.json
  def destroy
    @account_history.destroy
    respond_to do |format|
      format.html { redirect_to account_histories_url, notice: 'Account history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_history
      @account_history = AccountHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_history_params
      params.require(:account_history).permit(:account_id, :credit_rating)
    end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  before_action :set_auth, only: [:show, :edit, :update, :destroy]

  # GET /auths
  # GET /auths.json
  def index
    @auths = Auth.all
  end

  # GET /auths/1
  # GET /auths/1.json
  def show
  end

  # GET /auths/new
  def new
    @auth = Auth.new
  end

  # GET /auths/1/edit
  def edit
  end

  # POST /auths
  # POST /auths.json
  def create
    @auth = Auth.new(auth_params)

    respond_to do |format|
      if @auth.save
        format.html { redirect_to @auth, notice: 'Auth was successfully created.' }
        format.json { render :show, status: :created, location: @auth }
      else
        format.html { render :new }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auths/1
  # PATCH/PUT /auths/1.json
  def update
    respond_to do |format|
      if @auth.update(auth_params)
        format.html { redirect_to @auth, notice: 'Auth was successfully updated.' }
        format.json { render :show, status: :ok, location: @auth }
      else
        format.html { render :edit }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auths/1
  # DELETE /auths/1.json
  def destroy
    @auth.destroy
    respond_to do |format|
      format.html { redirect_to auths_url, notice: 'Auth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auth
      @auth = Auth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auth_params
      params.require(:auth).permit(:login, :password)
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def my_blog
  	render :layout => "my_layout"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def Phone_No
  	render :layout => "my_layout"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	#render "online_job_support/ROR_Job_support"
  	#redirect_to contact_Phone_No_path, :alert => "Developing"
  	#redirect_to online_training_Python_path, :notice => "My Page"
  end
 end

app/helpers/account_histories_helper.rb
module AccountHistoriesHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_forms_helper.rb
module MyFormsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/account_histories/_form.html.erb
<%= form_with(model: account_history, local: true) do |form| %>
  <% if account_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_history.errors.count, "error") %> prohibited this account_history from being saved:</h2>

      <ul>
      <% account_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, id: :account_history_account_id %>
  </div>

  <div class="field">
    <%= form.label :credit_rating %>
    <%= form.text_field :credit_rating, id: :account_history_credit_rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/account_histories/edit.html.erb
<h1>Editing Account History</h1>

<%= render 'form', account_history: @account_history %>

<%= link_to 'Show', @account_history %> |
<%= link_to 'Back', account_histories_path %>

app/views/account_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Histories</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Credit rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_histories.each do |account_history| %>
      <tr>
        <td><%= account_history.account_id %></td>
        <td><%= account_history.credit_rating %></td>
        <td><%= link_to 'Show', account_history %></td>
        <td><%= link_to 'Edit', edit_account_history_path(account_history) %></td>
        <td><%= link_to 'Destroy', account_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account History', new_account_history_path %>

app/views/account_histories/new.html.erb
<h1>New Account History</h1>

<%= render 'form', account_history: @account_history %>

<%= link_to 'Back', account_histories_path %>

app/views/account_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @account_history.account_id %>
</p>



<p>
  <strong>Account No:</strong>
 <%= @account_history.account.account_number %>
</p>


<p>
  <strong>Credit rating:</strong>
  <%= @account_history.credit_rating %>
</p>


<%= link_to 'Edit', edit_account_history_path(@account_history) %> |
<%= link_to 'Back', account_histories_path %>