config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :my_forms
  resources :auths
  resources :account_histories
  resources :accounts
  resources :suppliers
  resources :contacts
  get '/blog/my_blog'
  get 'home/web_page'
  get '/contact/Phone_No'
  get 'online_job_support/ROR_Job_support'
  get 'online_job_support/Ruby_cucumber_Job_Support'
  get 'online_training/RubyOnRails'
  get 'online_training/ruby_cucumber'
  get '/online_training/Python'
  get 'online_training/html_css_js'
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  #validates :name, :phone, :email, :address, presence: true
  #validates :email, format: { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i }
  #validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  #validates :email, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/ }
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def Phone_No
  	render :layout => "my_layout"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email, :address)
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contact/Phone_No.html.erb
<%= alert %>
<h1>Contact</h1>
<p>Contact me on 8017509423</p>

app/views/contact/_content.html.erb
<div id="content">

    <!-- Normal content: Stuff that's not going to be put in the left or right column. -->
    <div id="normalcontent">
      <h3><strong>Zenlike</strong><sup>1.0</sup> <span>by NodeThirtyThree</span></h3>
      <div class="contentarea">
        <!-- Normal content area start -->

        <%= image_tag("pic1.jpg", class: "left") %>
        <p>Zenlike<sup>1.0</sup> is a free, lightweight, tableless, fluid W3C-compliant website design by <a href="http://www.nodethirtythree.com/">NodeThirtyThree Design</a>. All photos came from <a href="http://www.pdphoto.org/">PDPhoto</a> and the background texture is from <a href="http://www.mayang.com/textures/">Mayang's texture site</a>. You're free to dissect, manipulate and use it to your heart's content. We only ask that you link back to <a href="http://www.nodethirtythree.com/">our site</a> in some way. If you find this design useful, feel free to let us know :)</p>
        <p>You can find more of our free work at this site or <a href="http://www.nodethirtythree.com/">our site</a>, or some of our commercial work on <a href="http://www.4templates.com/?aff=n33">4Templates.com</a>, a commercial website template site.</p>

        <!-- Normal content area end -->
      </div>
    </div>

app/views/contact/_divider.html.erb
<div class="divider2"></div>
    
        <div class="post">
          <h4>Consequat Odio Vestibulum</h4>
          <div class="contentarea">
            <div class="details">Posted by <a href="#">Jane Doe</a> on September 25, 2006</div> 
            <%= image_tag("pic3.jpg", class: "left") %>
            <p>Aenean felis quisque eros. Cras lobortis commodo lorem ipsum dolor. Vestibulum vel purus. In eget odio in sapien adipiscing blandit. Lorem ipsum dolor sit amet consequat etiam sed dolore.</p>
            <ul class="controls">
              <li><a href="#" class="printerfriendly">Printer Friendly</a></li>
              <li><a href="#" class="comments">Comments (18)</a></li>
              <li><a href="#" class="more">Read More</a></li>       
            </ul>
          </div>
        </div>

app/views/contact/_divider2.html.erb
<div class="divider2"></div>
    
        <div class="post">
          <h4>Adipiscing Nullam</h4>
          <div class="contentarea">
            <div class="details">Posted by <a href="#">Jane Doe</a> on September 25, 2006</div> 
            <p>Eget odio in sapien adipiscing blandit. Quisque augue tortor, facilisis sit amet, aliquam, suscipit vitae, cursus sed, arcu lorem ipsum dolor sit amet felis quisque eros. Cras lobortis commodo lorem ipsum dolor. Vestibulum vel purus. In eget odio in sapien adipiscing blandit. Quisque augue tortor, facilisis sit amet, aliquam, suscipit lorem ipsum dolor.</p>
            <ul class="controls">
              <li><a href="#" class="printerfriendly">Printer Friendly</a></li>
              <li><a href="#" class="comments">Comments (18)</a></li>
              <li><a href="#" class="more">Read More</a></li>       
            </ul>
          </div>
        </div>

app/views/contact/_footer.html.erb
<div id="footer">
      <div class="left">&copy; 2006 Your Website Name. All rights reserved.</div>
      <div class="right">Design by <a href="http://www.nodethirtythree.com/">NodeThirtyThree Design</a></div>
  </div>

app/views/contact/_header.html.erb
<div id="header">
    <div id="headercontent">
      <h1>Zenlike<sup>1.0</sup></h1>
      <h2>A free design by NodeThirtyThree</h2>
    </div>
  </div>


  <form method="post" action="">
    <div id="search">
      <input type="text" class="text" maxlength="64" name="keywords" />
      <input type="submit" class="submit" value="Search" />
    </div>
  </form>

app/views/contact/_headerpic.html.erb
<div id="headerpic"></div>

app/views/contact/_menu.html.erb
<div id="menu">
    <!-- HINT: Set the class of any menu link below to "active" to make it appear active -->
    <ul>
      <li><a href="/online_training/Python">Home</a></li>
      <li><a href="#" class="active">News</a></li>
      <li><a href="/blog/my_blog">Blog</a></li>
      <li><a href="#">Gallery</a></li>
      <li><% if admin_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
    </li>
         <% else %>
    <li>
      <%= link_to('Login', new_admin_session_path)  %>  
  </li>
        <% end %></li>
      <li><a href="/contacts/new">Contact</a></li>
    </ul>
  </div>
  <div id="menubottom"></div>

app/views/contact/_sec-content.html.erb
<div class="box">
        <h4>Blandit Veroeros</h4>
        <div class="contentarea">
          <%= image_tag("pic2.jpg", class: "left") %>
          <p>Sed etiam et lorem ipsum nulla vero et lobortis felis sed etiam. Lorem ipsum sit amet dolore. Nulla facilisi. Sed tortor. Aenean felis. Quisque eros etiam <a href="#">sed commodo</a>.</p>
        </div>
      </div>
    
      <div>
        <h4>Nullam Dolore</h4>
        <div class="contentarea">
          <ul class="linklist">
            <li><a href="#">Volutpat at varius sed</a></li>
            <li><a href="#">Sollicitudin et arcu</a></li>
            <li><a href="#">Vivamus viverra nullam</a></li>
            <li><a href="#">Turpis vestibulum</a></li>
            <li><a href="#">Sed etiam lorem ipsum</a></li>
            <li><a href="#">Sit amet dolore nulla</a></li>
            <li><a href="#">Facilisi sed tortor</a></li>
            <li><a href="#">Aenean felis quisque</a></li>
            <li><a href="#">Eros cras lobortis vel</a></li>
            <li><a href="#">Purus in eget odio sapien</a></li>
            <li><a href="#">Adipiscing blandit</a></li>
          </ul>
        </div>
      </div>