config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :my_forms
  resources :auths
  resources :account_histories
  resources :accounts
  resources :suppliers
  resources :contacts
  get '/blog/my_blog'
  get 'home/web_page'
  get '/contact/Phone_No'
  get 'online_job_support/ROR_Job_support'
  get 'online_job_support/Ruby_cucumber_Job_Support'
  get 'online_training/RubyOnRails'
  get 'online_training/ruby_cucumber'
  get '/online_training/Python'
  get 'online_training/html_css_js'
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :supplier, foreign_key: "supplier_id"
	has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
	belongs_to :account, foreign_key: "account_id"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth.rb
class Auth < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  #validates :name, :phone, :email, :address, presence: true
  #validates :email, format: { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i }
  #validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  #validates :email, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/ }
end

app/models/my_form.rb
class MyForm < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_one :account
	has_one :account_history, :through => :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_number, :supplier_id)
    end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  before_action :set_auth, only: [:show, :edit, :update, :destroy]

  # GET /auths
  # GET /auths.json
  def index
    @auths = Auth.all
  end

  # GET /auths/1
  # GET /auths/1.json
  def show
  end

  # GET /auths/new
  def new
    @auth = Auth.new
  end

  # GET /auths/1/edit
  def edit
  end

  # POST /auths
  # POST /auths.json
  def create
    @auth = Auth.new(auth_params)

    respond_to do |format|
      if @auth.save
        format.html { redirect_to @auth, notice: 'Auth was successfully created.' }
        format.json { render :show, status: :created, location: @auth }
      else
        format.html { render :new }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auths/1
  # PATCH/PUT /auths/1.json
  def update
    respond_to do |format|
      if @auth.update(auth_params)
        format.html { redirect_to @auth, notice: 'Auth was successfully updated.' }
        format.json { render :show, status: :ok, location: @auth }
      else
        format.html { render :edit }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auths/1
  # DELETE /auths/1.json
  def destroy
    @auth.destroy
    respond_to do |format|
      format.html { redirect_to auths_url, notice: 'Auth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auth
      @auth = Auth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auth_params
      params.require(:auth).permit(:login, :password)
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def my_blog
  	render :layout => "my_layout"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def Phone_No
  	render :layout => "my_layout"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	#render "online_job_support/ROR_Job_support"
  	#redirect_to contact_Phone_No_path, :alert => "Developing"
  	#redirect_to online_training_Python_path, :notice => "My Page"
  end
 end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_forms_helper.rb
module MyFormsHelper
end

app/helpers/online_training_helper.rb
module OnlineTrainingHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.text_field :supplier_id, id: :account_supplier_id %>
  </div>

  <div class="field">
    <%= form.label :account_number %>
    <%= form.text_field :account_number, id: :account_account_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Account number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.supplier_id %></td>
        <td><%= account.account_number %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @account.supplier_id %>
</p>

<p>
  <strong>Account No:</strong>
  <%= @account.account_number %>
</p>

<p>
  <strong>Supplier Name:</strong>
  <%= @account.supplier.name %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/auths/_form.html.erb
<%= form_with(model: auth, local: true) do |form| %>
  <% if auth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auth.errors.count, "error") %> prohibited this auth from being saved:</h2>

      <ul>
      <% auth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :auth_login %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :auth_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/auths/edit.html.erb
<h1>Editing Auth</h1>

<%= render 'form', auth: @auth %>

<%= link_to 'Show', @auth %> |
<%= link_to 'Back', auths_path %>

app/views/auths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auths</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auths.each do |auth| %>
      <tr>
        <td><%= auth.login %></td>
        <td><%= auth.password %></td>
        <td><%= link_to 'Show', auth %></td>
        <td><%= link_to 'Edit', edit_auth_path(auth) %></td>
        <td><%= link_to 'Destroy', auth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auth', new_auth_path %>

app/views/auths/new.html.erb
<h1>New Auth</h1>

<%= render 'form', auth: @auth %>

<%= link_to 'Back', auths_path %>

app/views/auths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @auth.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @auth.password %>
</p>

<%= link_to 'Edit', edit_auth_path(@auth) %> |
<%= link_to 'Back', auths_path %>